/*
 * Cloudflare Pages `_headers`, as data.
 *
 * **One declaration, three consumers**: the file written into the export, the
 * local server that applies them so the CSP is exercised before it ships, and
 * the check that asserts the page still works under them. A `_headers` file
 * written by hand and a local server that ignores it are two states of the
 * world, and the one that gets tested is the permissive one — so the first
 * time the real CSP runs is in production, on a page nobody can fix quickly.
 *
 * ---
 *
 * **The CSP is derived from what the site actually does**, which is very
 * little: a static export with no third-party script, no analytics SDK, no
 * font CDN and no embedded frame. `script-src 'self'` holds because Next's
 * App Router emits its bootstrap as external chunks rather than inline script.
 * `style-src` carries `'unsafe-inline'` and that is not laziness — Next inlines
 * a `<style>` block for the critical CSS, and the alternative is a per-build
 * nonce, which a static export has nowhere to put.
 *
 * `connect-src 'self'` is what lets `/api/plan` be called and nothing else. It
 * is the line that makes the "tuning is fully local, zero network requests"
 * claim enforceable by the browser rather than only by a test.
 */

export interface HeaderRule {
  readonly path: string
  readonly headers: Readonly<Record<string, string>>
  /** Why, in one line. Written into `_headers` as a comment. */
  readonly why: string
}

function csp(scriptHashes: readonly string[]): string {
  return [
  "default-src 'self'",
  ["script-src 'self'", ...scriptHashes.map((h) => `'${h}'`)].join(' '),
  // Next inlines critical CSS; a static export has nowhere to put a nonce.
  "style-src 'self' 'unsafe-inline'",
  // The grain is an inline feTurbulence data URI (§12.3a).
  "img-src 'self' data:",
  "font-src 'self'",
  // `/api/plan` and nothing else. No third party, no beacon, no SDK.
  "connect-src 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
  ].join('; ')
}

/**
 * @param scriptHashes `sha256-…` values for every inline script in the export.
 * Empty is legal and produces a policy that blocks them — which is correct for
 * a page with none, and is why `check-csp.mjs` asserts the page still works
 * rather than only that the header is present.
 */
export function headerRules(scriptHashes: readonly string[] = []): readonly HeaderRule[] {
  return [
  {
    path: '/*',
    why: 'Baseline security headers for every document.',
    headers: {
      'Content-Security-Policy': csp(scriptHashes),
      'X-Content-Type-Options': 'nosniff',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
      /*
       * Every powerful feature this site does not use, denied. The list is not
       * decoration: a permissions policy naming only what you use tells an
       * attacker nothing and denies nothing. Microphone is here because the app
       * PRD records it as a permanent no rather than a deferral, and the site
       * should not be able to contradict that even by accident.
       */
      'Permissions-Policy':
        'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()',
      'Cross-Origin-Opener-Policy': 'same-origin',
    },
  },
  {
    path: '/_next/static/*',
    why: 'Content-hashed by the build, so it can never be stale.',
    headers: { 'Cache-Control': 'public, max-age=31536000, immutable' },
  },
  {
    path: '/api/*',
    why: 'A plan depends on what the visitor typed; a shared cache would serve one to another.',
    headers: { 'Cache-Control': 'no-store' },
  },
  {
    path: '/og.png',
    why: 'Regenerated only when the card changes, and crawlers refetch it rarely.',
    headers: { 'Cache-Control': 'public, max-age=86400' },
  },
  ]
}

/** Render `_headers` in Cloudflare Pages' format. */
export function headersFile(scriptHashes: readonly string[] = []): string {
  const lines: string[] = [
    '# Generated by scripts/build-assets.ts from lib/deploy/headers.ts.',
    '# Edit the module, never this file.',
    '',
  ]
  for (const rule of headerRules(scriptHashes)) {
    lines.push(`# ${rule.why}`, rule.path)
    for (const [name, value] of Object.entries(rule.headers)) {
      lines.push(`  ${name}: ${value}`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

/** The rules that apply to a path, innermost last. */
export function headersFor(
  pathname: string,
  scriptHashes: readonly string[] = [],
): Record<string, string> {
  const out: Record<string, string> = {}
  for (const rule of headerRules(scriptHashes)) {
    const pattern = new RegExp(`^${rule.path.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*')}$`)
    if (pattern.test(pathname)) Object.assign(out, rule.headers)
  }
  return out
}
